//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonashBnB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ratingId { get; set; }
        public string ratingComment { get; set; }
        public short ratingStar { get; set; }
        public int userId { get; set; }
        public int hotelId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
