//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonashBnB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        public int roomTypeId { get; set; }
        public short roomTypeBedCount { get; set; }
        public short roomTypeBedroomCount { get; set; }
        public short roomTypeBathCount { get; set; }
        public short roomTypeAccomodateCount { get; set; }
        public string roomTypeName { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
